import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;
/**
 *
 * @author paulj
 */
public class splash extends javax.swing.JFrame {
Timer timer;
ActionListener action;
    /**
     * Creates new form splash
     */
     public splash() {
        this(null); // Panggil konstruktor utama dengan nextFrame = null
    }


    public splash(javax.swing.JFrame nextFrame) {
        this.setUndecorated(true);
        initComponents();
        setLocationRelativeTo(null);
        aksi(nextFrame);
        progress.setValue(0);
        timer = new Timer(100,action);
        timer.start();
    }
    
    private void aksi(javax.swing.JFrame nextFrame) {
        action = new ActionListener(){
            
            public void actionPerformed(ActionEvent e) {
                progress.setValue(progress.getValue() + 7 );
                progress.setStringPainted(true);
                if(progress.getPercentComplete()==1.0){
                    timer.stop();
                    dispose();
                    if (nextFrame != null) {
                        nextFrame.setVisible(true); //  
                }
             }
        }
    };
}
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        welcome = new javax.swing.JLabel();
        progress = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 102, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        welcome.setFont(new java.awt.Font("MV Boli", 1, 38)); // NOI18N
        welcome.setForeground(new java.awt.Color(0, 0, 255));
        welcome.setText("WELCOME");
        jPanel1.add(welcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, -1, -1));

        progress.setBackground(new java.awt.Color(255, 0, 51));
        progress.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jPanel1.add(progress, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 470, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bgimg.jpeg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new splash(new kasir()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar progress;
    private javax.swing.JLabel welcome;
    // End of variables declaration//GEN-END:variables
}
    
